package com.postgressql.postgressqlCRUD.repository.Repo;

import com.postgressql.postgressqlCRUD.repository.entity.ENTITY_TblWfWorkflowStageautocomplete;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

public interface ENTITY_TblWfWorkflowStageautocompleteRepository extends JpaRepository<ENTITY_TblWfWorkflowStageautocomplete, Integer>, JpaSpecificationExecutor<ENTITY_TblWfWorkflowStageautocomplete> {
}