package com.postgressql.postgressqlCRUD.repository.Repo;

import com.postgressql.postgressqlCRUD.repository.entity.ENTITY_TblCnfgMstSubproducts;
import com.postgressql.postgressqlCRUD.repository.entity.ENTITY_TblCnfgMstSubproductsPK;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

public interface ENTITY_TblCnfgMstSubproductsRepository extends JpaRepository<ENTITY_TblCnfgMstSubproducts, ENTITY_TblCnfgMstSubproductsPK>, JpaSpecificationExecutor<ENTITY_TblCnfgMstSubproducts> {
}